use_frameworks!

platform :ios, '8.0'

target 'GGMainSliderViewController_Example' do
  pod 'GGMainSliderViewController', :path => '../'

  target 'GGMainSliderViewController_Tests' do
    inherit! :search_paths

    
  end
end
